### ISSUE TITLE
execute build.sh go wrong,I used EOSIO release/1.3.x

### ISSUE THREAD

**Issue by licongxing** [EOSLaoMao/BankofStaked-CE#20]
### Error is as follows：
=======================================================
9462d416262c        eoslaomao/eos-dev:1.2.3   "/bin/bash"         2 minutes ago       Up 2 minutes                            bankofstaked-eos-dev
2018-10-27T07:46:32.075 thread-0   abi_generator.hpp:68          ricardian_contracts  ] Warning, no ricardian clauses found for 

In file included from /bankofstaked/src/bankofstaked.cpp:1:
In file included from /eos/contracts/eosiolib/currency.hpp:3:
/eos/contracts/eosiolib/asset.hpp:59:54: error: **use of undeclared identifier 'EOS'**
      explicit asset( int64_t a = 0, symbol_type s = CORE_SYMBOL )
                                                     ^
/eos/contracts/eosiolib/core_symbol.hpp:7:26: note: expanded from macro 'CORE_SYMBOL'
#define CORE_SYMBOL SY(4,EOS)
                         ^
In file included from /bankofstaked/src/bankofstaked.cpp:4:
/eos/contracts/eosio.system/eosio.system.hpp:126:56: error: use of undeclared identifier 'EOS'
   static constexpr uint64_t     system_token_symbol = CORE_SYMBOL;
                                                       ^
/eos/contracts/eosiolib/core_symbol.hpp:7:26: note: expanded from macro 'CORE_SYMBOL'
**#define CORE_SYMBOL SY(4,EOS)**
                         ^
2 errors generated.
Error while processing /bankofstaked/src/bankofstaked.cpp.
**Error: No such container: nodeosd**
lstat /home/laymond/code/bankofstaked: no such file or directory
lstat /home/laymond/code/bankofstaked: no such file or directory
lstat /home/laymond/code/bankofstaked: no such file or directory
Error: No such container:path: nodeosd:/
mv: 无法获取'bankofstaked.abi' 的文件状态(stat): 没有那个文件或目录
Build SUCCESS!!!
	=========== Building eosio.contracts ===========

CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    EosioWasmToolchain

CMake Error at CMakeLists.txt:29 (message):
  Incorrect EOSIO.WasmSDK version, please use version 1.1.x

-- Configuring incomplete, errors occurred!
See also "/home/laymond/code/BankofStaked-CE/tests/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
./unittest.sh: 行 8: ./build/tests/unit_test: 没有那个文件或目录
-----------------------------------
Please run ./build.sh first.
-----------------------------------
==========================================================

**Comment by JohnnyZhao** [comment]
try change the line in /eos/contracts/eosiolib/core_symbol.hpp:

from 

`#define CORE_SYMBOL SY(4,EOS)`

to 

`#define CORE_SYMBOL S(4,EOS)`

**Comment by licongxing** [comment]
> try change the line in /eos/contracts/eosiolib/core_symbol.hpp:
> 
> from
> 
> `#define CORE_SYMBOL SY(4,EOS)`
> 
> to
> 
> `#define CORE_SYMBOL S(4,EOS)`

ok,I change eoslaomao/eos-dev:1.2.3 core_symbol.hpp，this question is solved。but，There are new problems。as follow:
e0123aa003e9        eoslaomao/eos-dev:1.2.3   "/bin/bash"         About a minute ago   Up About a minute                       bankofstaked-eos-dev
2018-10-27T09:55:11.293 thread-0   abi_generator.hpp:68          ricardian_contracts  ] Warning, no ricardian clauses found for 

Generated /bankofstaked/bankofstaked.abi ...
Error: No such container: nodeosd
lstat /home/laymond/code/bankofstaked: no such file or directory
lstat /home/laymond/code/bankofstaked: no such file or directory
lstat /home/laymond/code/bankofstaked: no such file or directory
Error: No such container:path: nodeosd:/
Build SUCCESS!!!
	=========== Building eosio.contracts ===========

CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    EosioWasmToolchain


CMake Error at CMakeLists.txt:29 (message):
  Incorrect EOSIO.WasmSDK version, please use version 1.1.x


-- Configuring incomplete, errors occurred!
See also "/home/laymond/code/BankofStaked-CE/tests/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
./unittest.sh: 行 8: ./build/tests/unit_test: 没有那个文件或目录
-----------------------------------
Please run ./build.sh first.
-----------------------------------

**Comment by JohnnyZhao** [comment]
it's unit test that failed building, the abi and wasm should be built successfully.

**Comment by JohnnyZhao** [comment]
which is ready to deploy

**Comment by licongxing** [comment]
i see the **build.sh**，
`
#!/bin/bash
IMAGE=eoslaomao/eos-dev:1.2.3
NAME=bankofstaked
FOLDER=bankofstaked

docker ps | grep $NAME-eos-dev
if [ $? -ne 0 ]; then
    echo "Run eos dev env "
    docker run --name $NAME-eos-dev -dit --rm -v  `(pwd)`:/$NAME $IMAGE
fi

docker exec $NAME-eos-dev eosiocpp -g /$NAME/$NAME.abi /$NAME/src/$NAME.cpp
docker exec $NAME-eos-dev eosiocpp -o /$NAME/$NAME.wast /$NAME/src/$NAME.cpp
**docker exec nodeosd mkdir /$NAME**
docker cp ../$FOLDER/$NAME.abi nodeosd:/$NAME/
docker cp ../$FOLDER/$NAME.wasm nodeosd:/$NAME/
docker cp ../$FOLDER/$NAME.wast nodeosd:/$NAME/
docker cp scripts nodeosd:/


#run unit test
if [ ! -d build ]; then
    mkdir build
    echo "Create build dir!!"
fi

mv $NAME.abi ./build
mv $NAME.wast ./build
mv $NAME.wasm ./build

echo "Build SUCCESS!!!"

./unittest.sh
`
eoslaomao/eos-dev:1.2.3，that is not had container:nodeosd!!!!

**Comment by licongxing** [comment]
in the build.sh,docker exec nodeosd mkdir /$NAME
nodeosd is which container ? eosio/eos?

**Comment by licongxing** [comment]
> > in the build.sh,docker exec nodeosd mkdir /$NAME
> > nodeosd is which container ? eosio/eos?
> 
> this is a custom setup just for me, nodeosd is a container running on my dev env, so you can just ignore it

就是说，下面几句 可以屏蔽掉吗？
`
 14 docker exec nodeosd mkdir /$NAME
 15 docker cp ../$FOLDER/$NAME.abi nodeosd:/$NAME/
 16 docker cp ../$FOLDER/$NAME.wasm nodeosd:/$NAME/
 17 docker cp ../$FOLDER/$NAME.wast nodeosd:/$NAME/
 18 docker cp scripts nodeosd:/

`

**Comment by JohnnyZhao** [comment]
> > > in the build.sh,docker exec nodeosd mkdir /$NAME
> > > nodeosd is which container ? eosio/eos?
> > 
> > 
> > this is a custom setup just for me, nodeosd is a container running on my dev env, so you can just ignore it
> 
> 就是说，下面几句 可以屏蔽掉吗？
> `
> 14 docker exec nodeosd mkdir /$NAME
> 15 docker cp ../$FOLDER/$NAME.abi nodeosd:/$NAME/
> 16 docker cp ../$FOLDER/$NAME.wasm nodeosd:/$NAME/
> 17 docker cp ../$FOLDER/$NAME.wast nodeosd:/$NAME/
> 18 docker cp scripts nodeosd:/
> 
> `

YES
