### ISSUE TITLE
clearhistory接口疑似有一个bug

### ISSUE THREAD

**Issue by wangyilin1987** [EOSLaoMao/BankofStaked-CE#25]
`  void clearhistory()
  {
    require_auth(code_account);
    uint64_t depth = 0;
    history_table o(code_account, SCOPE_ORDER>>1);
    while (o.begin() != o.end())
    {
      depth += 1;
      if(depth >100) {
        break;
      }
      auto itr = o.end();
      itr--;
      o.erase(itr);
      order_table o(code_account, SCOPE_ORDER>>1);
    }
  }`
其中的 order_table o(code_account, SCOPE_ORDER>>1);表名是不是写错了？

**Comment by JohnnyZhao** [comment]
已经修复，感谢。
