### ISSUE TITLE
Contract depends on deprecated currency.hpp struct

### ISSUE THREAD

**Issue by fproulx-eoscanada** [EOSLaoMao/BankofStaked-CE#9]
You depend on the deprecated  (https://github.com/EOSIO/eosio.cdt/pull/56) `currency.hpp`  file which was erroneously included in the `eoslib`. This prevents from building the contract with the `v1.2.x` EOS CDT.

I guess you instead should copy `eosio.token.hpp`'s `transfer_args` struct (https://github.com/EOSIO/eosio.contracts/blob/master/eosio.token/include/eosio.token/eosio.token.hpp#L66-L71) to your project ?

**Comment by JohnnyZhao** [comment]
Thanks! will dive into that ASAP

**Comment by JohnnyZhao** [comment]
alright, migrated to cdt 1.4.x

**Comment by novalina26** [comment]
> You depend on the deprecated ([EOSIO/eosio.cdt#56](https://github.com/EOSIO/eosio.cdt/pull/56)) `currency.hpp` file which was erroneously included in the `eoslib`. This prevents from building the contract with the `v1.2.x` EOS CDT.
> 
> I guess you instead should copy `eosio.token.hpp`'s `transfer_args` struct (https://github.com/EOSIO/eosio.contracts/blob/master/eosio.token/include/eosio.token/eosio.token.hpp#L66-L71) to your project ?
